name: rsa_digitalsignature
description: A plugin for signing data with privateKey RSACNG for windows & MacOS.
version: 1.0.1
homepage: https://github.com/waelwederni4/RSADigitalSignatureFlutter

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  x509: ^0.2.4
  asn1lib: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: RsaDigitalsignaturePlugin
      windows:
        pluginClass: RsaDigitalsignaturePluginCApi
